@startuml

actor User
User -> CommandChangeLearned **: executeCommand()
CommandChangeLearned -> Deck: changeIsLearned()
return
CommandChangeLearned -> Ui: showToUser(changed isLearned value)
return

CommandChangeLearned --> User


@enduml