@startuml

hide footbox
participant "<<class>>\n :FlashCLI" as FlashCLI
participant "c:CommandCreateFlashcard" as CommandCreateFlashcard
participant ":Deck" as Deck
participant ":Flashcard" as Flashcard
participant ":Ui" as Ui

FlashCLI -> CommandCreateFlashcard: executeCommand()
activate CommandCreateFlashcard
CommandCreateFlashcard -> Deck: createFlashcard()

activate Deck

Deck -> Deck: checkQuestionAndAnswer()
activate Deck

Deck --> Deck: question and answer
deactivate Deck

create Flashcard
Deck -> Flashcard
activate Flashcard
Flashcard-->Deck
deactivate Flashcard
Deck --> CommandCreateFlashcard: success message
deactivate Deck
CommandCreateFlashcard -> Ui: showToUser()
activate Ui
Ui --> CommandCreateFlashcard
deactivate Ui
CommandCreateFlashcard --> FlashCLI
deactivate CommandCreateFlashcard
destroy CommandCreateFlashcard

@enduml
