@startuml

hide footbox
participant "<<class>> \n:FlashCLI" as FlashCLI
participant "c:CommandCreateDeck" as CommandCreateDeck
participant "<<class>> \n :DeckManager" as DeckManager
participant ":FlashCLIArgumentException" as FlashCLIArgumentException
participant ":Deck" as Deck

FlashCLI -> CommandCreateDeck: executeCommand()
activate CommandCreateDeck
CommandCreateDeck -> DeckManager: createDeck(...)
activate DeckManager

alt invalid or duplicate deck name
    DeckManager -> FlashCLIArgumentException
    activate FlashCLIArgumentException
    deactivate FlashCLIArgumentException

else else
    create Deck
    DeckManager -> Deck
    activate Deck
    Deck --> DeckManager
    deactivate Deck
    DeckManager --> CommandCreateDeck : success message
    deactivate DeckManager
    CommandCreateDeck --> FlashCLI
    deactivate CommandCreateDeck
    destroy CommandCreateDeck
end alt

@enduml
