@startuml
hide circle
skinparam classAttributeIconSize 0
class CommandDelete {
  - String arguments
  + executeCommand()
}

class Deck {
  + deleteFlashcard(int): String
}

CommandDelete --> Deck
@enduml