@startuml
actor User
activate Flashcard
User -> CommandEdit : executeCommand()
activate CommandEdit
CommandEdit -> Ui : showToUser()
activate Ui
return
CommandEdit -> Flashcard : editFlashcard(int, String)
deactivate CommandEdit
@enduml