@startuml
actor User
activate Flashcard
User -> CommandEdit : executeCommand()
activate CommandEdit
CommandEdit -> UI : showToUser()
activate UI
return
CommandEdit -> Flashcard : editFlashcard(int, String)
deactivate CommandEdit
@enduml