@startuml
actor User
User -> CommandQuizFlashcards **: executeCommand()
CommandQuizFlashcards++
CommandQuizFlashcards -> Deck++: quizFlashcards()
Deck -> Timer **
Timer ++
loop [flashcards.size()]
    alt [unlearned]
    Deck -> Deck++: handleQuestion
    Deck -> Ui++: showToUser(question)
    return
    Deck -> Deck++: handleAnswer
    return
    Deck -> Timer: get the time taken for question
    Timer --> Deck
    Deck -> Ui++ : showToUser( correct? statement + time taken for question)
    return
    return
    end
end
return total duration

Deck -> Ui++ : showToUser(quiz ended + duration)
return
Deck --> CommandQuizFlashcards
CommandQuizFlashcards --> User


@enduml