@startuml
actor User
User -> CommandQuizFlashcards **: executeCommand()
CommandQuizFlashcards++
CommandQuizFlashcards -> Deck++: quizFlashcards()
loop [flashcards.size()]
    alt [unlearned]
    Deck -> Deck++: handleQuestion
    Deck -> Deck++: handleAnswer
    return
    return
    end
end
return

CommandQuizFlashcards --> User


@enduml