@startuml

hide footbox
participant "<<class>>\n :FlashCLI" as FlashCLI
participant ":CommandRenameDeck" as CommandRenameDeck
participant "<<class>>\n :DeckManager" as DeckManager
participant Deck

FlashCLI -> CommandRenameDeck: executeCommand()
activate CommandRenameDeck
CommandRenameDeck -> DeckManager: renameDeck()
activate DeckManager

DeckManager -> DeckManager:validateNewDeckName()
activate DeckManager
DeckManager --> DeckManager
deactivate DeckManager

DeckManager -> DeckManager:renameDeckInCollection()
activate DeckManager

DeckManager -> Deck: setName()
activate Deck
Deck --> DeckManager
deactivate Deck
DeckManager --> DeckManager
deactivate DeckManager

DeckManager --> CommandRenameDeck: success message
deactivate DeckManager
CommandRenameDeck --> FlashCLI
deactivate CommandRenameDeck
destroy CommandRenameDeck

@enduml
