@startuml
actor User
User -> CommandViewQuestion **: executeCommand()
CommandViewQuestion -> Deck: viewFlashcardQuestion()
Deck --> CommandViewQuestion: String question
CommandViewQuestion -> Ui: showToUser(question)


CommandViewQuestion -> User


@enduml