@startuml
hide circle
skinparam classAttributeIconSize 0
class CommandViewAnswer {
  - String arguments
  + executeCommand()
}

class Deck {
  + viewFlashcardAnswer(int): String
}

CommandViewAnswer --> Deck
@enduml