@startuml
actor User
participant ":CommandViewAnswer" as CommandViewAnswer
participant ":Deck" as Deck
participant ":Ui" as Ui
User -> CommandViewAnswer : executeCommand()
CommandViewAnswer -> Deck : viewFlashcardAnswer(index)
Deck -> CommandViewAnswer : answer string
CommandViewAnswer -> Ui : showToUser(answer)
@enduml